spring:
  datasource:
    # url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:mysql://localhost:3306/market
    username: root
    password: root
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
   port: 8080 # This is the default port anyway, but you can change it here

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
      
UserController:
  signin: Authenticates user and returns its JWT token
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data

ProductController:
  create: Creates a new product
  readById: Returns one product
  updateById: Updates a product
  readAll: Returns all products

PaymentController:
  create: Creates a new payment
  readById: Returns one payment
  readAll: Returns all payments

ReportController:
  readByType: Returns reports by type
  requestByType: Requests a new report by its type

CustomerOrderController:
  create: Creates a new customerOrder
  readById: Returns one customerOrder
  readAll: Returns all customerOrders

OrderDetailsController:
  create: Creates new orderDetails
  readById: Returns one orderDetails
  updateById: Updates a orderDetails
  readAll: Returns all orderDetailss

AlertController:
  readAll: Returns all alerts
